<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{aa14506c-e177-4d89-94bf-b04e2e20aa7f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	counter : INT := 0;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[counter := counter + 1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>