<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{6dd6ae82-dd44-4e79-8cfe-c1b243a8067c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fb_statemachine : FB_StateMachine;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fb_statemachine();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>